"""
Django settings for mscube project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from django.core.exceptions import ImproperlyConfigured

load_dotenv()


def getenv_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default

    normalized = value.strip().lower()
    if normalized in {'1', 'true', 'yes', 'on'}:
        return True
    if normalized in {'0', 'false', 'no', 'off'}:
        return False

    raise ImproperlyConfigured(
        f"Invalid boolean value for {name}: {value}. Use one of true/false, 1/0, yes/no, on/off."
    )


def getenv_float(name, default=None):
    value = os.getenv(name)
    if value is None:
        return default

    try:
        return float(value)
    except ValueError as exc:
        raise ImproperlyConfigured(
            f"Invalid float value for {name}: {value}."
        ) from exc


def getenv_int(name, default=None):
    value = os.getenv(name)
    if value is None:
        return default

    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(
            f"Invalid integer value for {name}: {value}."
        ) from exc

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getenv_bool('DEBUG', True)

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()]

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    
    # Third-party apps
    'allauth',
    'allauth.account',
    'axes',  # Login attempt tracking
    # 'django_ratelimit',  # Rate limiting (TODO: Configure Redis for production)
    
    # Local apps
    'core.apps.CoreConfig',
    'gym_website.apps.GymWebsiteConfig',
    'accounts.apps.AccountsConfig',
    'gym_management.apps.GymManagementConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'gym_management.middleware.security_headers.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for allauth
    'gym_management.middleware.audit.AuditMiddleware',
    'axes.middleware.AxesMiddleware',  # Must be last
]

ROOT_URLCONF = 'mscube.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_role_context',  # Inject user_role for navbar
            ],
        },
    },
]

WSGI_APPLICATION = 'mscube.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# PostgreSQL configuration (production)
if os.getenv('USE_POSTGRES', 'False') == 'True':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'mscube_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # SQLite (development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    } 

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# user uploaded media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Gym geofencing and QR session settings
GYM_LATITUDE = getenv_float('GYM_LATITUDE', 0.0 if DEBUG else None)
GYM_LONGITUDE = getenv_float('GYM_LONGITUDE', 0.0 if DEBUG else None)
GYM_RADIUS_METERS = getenv_float('GYM_RADIUS_METERS', 100.0)
GYM_QR_SESSION_TTL_SECONDS = getenv_int('GYM_QR_SESSION_TTL_SECONDS', 60)

if GYM_LATITUDE is None or GYM_LONGITUDE is None:
    raise ImproperlyConfigured(
        'GYM_LATITUDE and GYM_LONGITUDE must be configured for attendance geolocation validation.'
    )

if GYM_RADIUS_METERS is None or GYM_RADIUS_METERS <= 0:
    raise ImproperlyConfigured('GYM_RADIUS_METERS must be greater than 0.')

if GYM_QR_SESSION_TTL_SECONDS is None or GYM_QR_SESSION_TTL_SECONDS <= 0:
    raise ImproperlyConfigured('GYM_QR_SESSION_TTL_SECONDS must be greater than 0.')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== CACHE SETTINGS ====================

# Cache configuration (Redis for persistent rate limiting in production)
USE_REDIS = getenv_bool('USE_REDIS', False)

if USE_REDIS:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'mscube_cache',
            'TIMEOUT': 300,  # Default cache timeout (5 minutes)
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'mscube-cache',
        }
    }

# ==================== AUTHENTICATION SETTINGS ====================

# Site ID for django.contrib.sites
SITE_ID = 1

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    # Django default (username/password)
    'django.contrib.auth.backends.ModelBackend',
    # Allauth (account authentication)
    'allauth.account.auth_backends.AuthenticationBackend',
    # Axes (for tracking failed logins)
    'axes.backends.AxesStandaloneBackend',
]

# Django Allauth Settings (Updated for django-allauth >= 0.63)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # Allow login with username or email

ACCOUNT_EMAIL_VERIFICATION_MODE = os.getenv('ACCOUNT_EMAIL_VERIFICATION_MODE', 'mandatory').strip().lower()
ALLOWED_EMAIL_VERIFICATION_MODES = {'mandatory', 'optional', 'none'}
if ACCOUNT_EMAIL_VERIFICATION_MODE not in ALLOWED_EMAIL_VERIFICATION_MODES:
    raise ImproperlyConfigured(
        'Invalid ACCOUNT_EMAIL_VERIFICATION_MODE. Allowed values: mandatory, optional, none.'
    )

# Production safety guard: mandatory verification cannot be relaxed in production.
# During development/testing, set DEBUG=True to allow optional or none.
# In all production deployments (DEBUG=False), this value must be "mandatory" or the
# server will refuse to start.
if not DEBUG and ACCOUNT_EMAIL_VERIFICATION_MODE != 'mandatory':
    raise ImproperlyConfigured(
        "Email verification must be mandatory in production. "
        "Set ACCOUNT_EMAIL_VERIFICATION_MODE=mandatory or keep DEBUG=True for development/testing."
    )

account_email_required = getenv_bool('ACCOUNT_EMAIL_REQUIRED', True)
ACCOUNT_EMAIL_VERIFICATION = ACCOUNT_EMAIL_VERIFICATION_MODE

ACCOUNT_SIGNUP_FIELDS = ['username*', 'password1*', 'password2*']
if account_email_required:
    ACCOUNT_SIGNUP_FIELDS.insert(0, 'email*')
else:
    ACCOUNT_SIGNUP_FIELDS.insert(0, 'email')

ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 failed logins per 5 minutes
}

ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'

# Login/Logout URLs
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Email Backend
USE_SMTP_EMAIL = os.getenv('USE_SMTP_EMAIL', 'False') == 'True'

if USE_SMTP_EMAIL or not DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@mscubefitness.com')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Django Axes Settings (Brute Force Protection)
AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts
AXES_COOLOFF_TIME = 1  # Lock for 1 hour
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']  # Lock by both username and IP
AXES_RESET_ON_SUCCESS = True

# ==================== eSewa Payment Gateway Settings ====================
# eSewa Merchant ID - get from eSewa merchant dashboard
ESEWA_MERCHANT_ID = os.getenv('ESEWA_MERCHANT_ID', 'EPAYTEST')

# eSewa Secret Key - NEVER commit real key to version control
ESEWA_SECRET_KEY = os.getenv('ESEWA_SECRET_KEY', '8gBm/:&EnhH.1/q')

# eSewa Base URL - use sandbox for testing, production URL for live
# Sandbox: https://rc-epay.esewa.com.np
# Production: https://epay.esewa.com.np
ESEWA_BASE_URL = os.getenv('ESEWA_BASE_URL', 'https://rc-epay.esewa.com.np')

# Email settings for notifications
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@mscube.com')


# Security Settings (Production)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    CSRF_TRUSTED_ORIGINS = [
        origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()
    ]

LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'security.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'security.audit': {
            'handlers': ['console', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.security.production_guardrails': {
            'handlers': ['console', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ==================== PRODUCTION SECURITY GUARDRAILS ====================
# Validates all security-critical settings at startup.
# No-op when DEBUG=True (development / CI / testing environments).
# Raises ImproperlyConfigured on the first failing rule when DEBUG=False.
from core.security.production_guardrails import validate_production_settings  # noqa: E402
validate_production_settings(globals())
